# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import example as module_0


def test_case_0():
    bool_0 = True
    int_0 = -2906
    str_0 = module_0.triangle(bool_0, bool_0, int_0)
    assert str_0 == "Isosceles triangle"


def test_case_1():
    bool_0 = True
    none_type_0 = None
    str_0 = module_0.triangle(bool_0, none_type_0, bool_0)
    assert str_0 == "Isosceles triangle"


def test_case_2():
    int_0 = 498
    str_0 = module_0.triangle(int_0, int_0, int_0)
    assert str_0 == "Equilateral triangle"
    int_1 = 1602
    int_2 = 2078
    str_1 = module_0.triangle(int_1, str_0, int_2)
    assert str_1 == "Scalene triangle"


def test_case_3():
    int_0 = -906
    int_1 = -1775
    str_0 = module_0.triangle(int_0, int_0, int_1)
    assert str_0 == "Isosceles triangle"
    none_type_0 = None
    str_1 = module_0.triangle(int_1, int_0, none_type_0)
    assert str_1 == "Scalene triangle"


def test_case_4():
    none_type_0 = None
    bool_0 = True
    bool_1 = True
    bool_2 = False
    str_0 = module_0.triangle(bool_1, bool_2, bool_1)
    assert str_0 == "Isosceles triangle"
    str_1 = module_0.triangle(none_type_0, bool_0, bool_0)
    assert str_1 == "Isosceles triangle"
